### ISSUE TITLE
*** _pickle.UnpicklingError: invalid load key, '\x1f'. when loading image_encoder_bird.pth

### ISSUE THREAD

**Issue by jinx2018** [idealwhite/tdanet#1]
Hi!
When i reproducing your code, error occurs  

> *** _pickle.UnpicklingError: invalid load key, '\x1f'.
When  loading `image_encoder_bird.pth` using `torch.load`
But loading `image_encoder_coco.pth` is fine
So would you please  re-upload this file or help check this problem?

**Comment by idealwhite** [comment]
The old image_encoder_bird.pth file was broken, and has been updated in the current rar file.  You may download the current version and have a test.

**Comment by jinx2018** [comment]
Thank you so much,
