### ISSUE TITLE
How to run the GUI operation in the debug mode?

### ISSUE THREAD

**Issue by zzxzzx123** [idealwhite/tdanet#3]
Thanks for your code. I wonder if you can introduce how to run the GUI operation in the debug mode more specifically？

**Comment by idealwhite** [comment]
In practice, I add a debug line `import ipdb; ipdb.set_trace()` in ui_model.py at line 321. You can the GUI with the command:
`python ui_main.py --img_file ./datasets/CUB_200_2011/valid.flist --no_variance --display_port 8000  --gpu_id -1 --results_dir result/ --model tdanet
`
The program will stop at line 321 during inpainting, then you need to input ''c'' at the debug console to get the completed image. 

## Operation on UI 
![image](https://user-images.githubusercontent.com/16694969/112482107-a9f47f00-8db2-11eb-8262-d4c0b1645630.png)

## Why using the debug code 
In my desktop, the PyQt5 will dump without the debug code at 321, telling no error info for the python code. Stop at line 321 and then continue could avoid the problem.
