### ISSUE TITLE
hi there  ,thanks for you code

### ISSUE THREAD

**Issue by cccxyc** [idealwhite/tdanet#4]
i want to ask about the output image with '_rec' because i found it a lot more better and resonable than the output with '_out'.
i have only made some modification to the image_encoder, would you tell me how to fix this issue and how the TextualResGenerator outputs?
![image](https://user-images.githubusercontent.com/69033868/113994445-f9917b00-9887-11eb-9520-5713896ba30b.png)
![image](https://user-images.githubusercontent.com/69033868/113994978-66a51080-9888-11eb-8187-481047301b57.png)
![image](https://user-images.githubusercontent.com/69033868/113995050-7a507700-9888-11eb-90c9-d1fad1133c19.png)

**Comment by cccxyc** [comment]
well i went desperate and try testing ending up with good results

**Comment by idealwhite** [comment]
Sorry for the late response. The '_rec' results are usually good but they are not produced under the inpainting task. They are generated with the condition of I_rec and I_msk, as the "auxliiary path" in the paper.
