### ISSUE TITLE
关于输入文字进行修复实验

### ISSUE THREAD

**Issue by cj17SUI** [idealwhite/tdanet#5]
你好，最近看到您的文章，觉得您的研究思路以及实验效果都非常棒，对于您的研究非常感兴趣，有个问题想请教您：就是如何进行可输入文字对测试图片进行修复？

**Comment by idealwhite** [comment]
谢谢关注！你问的可输入文字是指文章中manipulation的实验吗？manipulation实验可以参照[GUI](https://github.com/idealwhite/tdanet#gui)部分的说明来进行操作。如果是其他问题欢迎进一步说明。

**Comment by cj17SUI** [comment]
十分感谢您的回答，刚按照您的操作说明测试了这个实验，但是出现了一个问题，FileNotFoundError: [Errno 2] No such file or directory: './datasets/CUB_200_2011/cate_image_train.json'，请问你这边还有cate_image_train.json这个文件吗，如果有，可以发给我一下吗，谢谢您

**Comment by cj17SUI** [comment]
> 谢谢关注！你问的可输入文字是指文章中manipulation的实验吗？manipulation实验可以参照[GUI](https://github.com/idealwhite/tdanet#gui)部分的说明来进行操作。如果是其他问题欢迎进一步说明。

十分感谢您的回答，刚按照您的操作说明测试了这个实验，但是出现了一个问题，FileNotFoundError: [Errno 2] No such file or directory: './datasets/CUB_200_2011/cate_image_train.json'，请问你这边还有cate_image_train.json这个文件吗，如果有，可以发给我一下吗，谢谢您

**Comment by idealwhite** [comment]
这是项目初期的一个无用的文件，但是这个文件应该不是运行所需要的（我运行实验的机器上并没有存留这个文件）。你可以尝试删去global_config.py中的line 37和line38行，如果无法解决问题我会把文件上传的GoogleDrive。（另外，注意checkpoint的命名方式，我在说明手册中做了更新）

**Comment by cj17SUI** [comment]
谢谢您热情地回答，我尝试地删除了global_config.py中的line 37和line38行，但是依旧无法解决该问题，会报一个错误
Traceback (most recent call last):
  File "E:\seconed\tdanet-master\gui\ui_model.py", line 151, in load_model
    with open(text_config.CATE_IMAGE_TRAIN, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by cj17SUI** [comment]
> 这是项目初期的一个无用的文件，但是这个文件应该不是运行所需要的（我运行实验的机器上并没有存留这个文件）。你可以尝试删去global_config.py中的line 37和line38行，如果无法解决问题我会把文件上传的GoogleDrive。（另外，注意checkpoint的命名方式，我在说明手册中做了更新）

谢谢您热情地回答，我尝试地删除了global_config.py中的line 37和line38行，但是依旧无法解决该问题，会报一个错误
Traceback (most recent call last):
File "E:\seconed\tdanet-master\gui\ui_model.py", line 151, in load_model
with open(text_config.CATE_IMAGE_TRAIN, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
